export const CATEGORIES = {
  PETARDOS: "Petardos",
  FOSFOROS: "Fosforos",
  BATERIAS: "Baterias",
  ESTALLOS_E_INFANTILES: "Estallos E Infantiles",
  VARIOS: "Varios",
  BOMBAS: "Bombas",
  GIRATORIOS_Y_VOLADORES: "Giratorios Y Voladores",
  MORTEROS: "Morteros",
  TRES_TIROS_Y_GIRANDOLAS: "Tres Tiros Y Girandolas",
  MISILES_Y_SILBADORES: "Misiles Y Silbadores",
  CANDELAS: "Candelas",
  BENGALAS: "Bengalas",
  ESTRELLITAS: "Estrellitas",
  VOLCANES: "Volcanes",
  CANAS_VOLADORAS: "Cañas Voladoras",
  TORTAS: "Tortas",
};
